### ISSUE TITLE
config.yml | spawn: 0-4-0 with negative coordinate not working

### ISSUE THREAD

**Issue by Steve41007** [asnover/Transfer-Service#1]
File: config.yml 
Variable: spawn: 0-4-0

Problem: When this variable is set to a negativ coordinat like 0--59-0 the plugin will throw an error at server-start and resets to default coordinats 0-4-0.

Everyting with a positiv number will be finde. But negative coordinates wont last a server reboot. If you adjust the coordinates while server is running, the negative ones will work fine until server reboot.

Server: Paper 3.3.0 -> Minecraft 1.20.4

**Comment by asnover** [comment]
Oh yeah. That was definitely a huge oversight on my part. Working on a fix now.

**Comment by asnover** [comment]
This bug has been fixed in version 1.0.5
