### ISSUE TITLE
unable to use vanilla transfer command

### ISSUE THREAD

**Issue by wilderop** [asnover/Transfer-Service#9]
please change the default command, I would like to also be able to use the vanilla transfer command. maybe /service or /transferservice /ts

**Comment by asnover** [comment]
Is there a specific reason as to why you need the vanilla transfer command? I am also just learning about this command so I'm going to research it a bit.

**Comment by wilderop** [comment]
I realized that we can use minecraft:transfer to use the vanilla command.

To answer your question, we use vanilla transfer to move players to
"partner" servers that are run by other server owners we are friendly with.
